# Generated by Django 5.2.5 on 2025-10-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='stacks',
            new_name='tech_stack',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ongoing', 'En cours'), ('completed', 'Terminé'), ('planned', 'Planifié')], default='planned', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stack',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
