# Generated by Django 5.2.5 on 2025-10-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker_1', '0002_rename_stacks_project_tech_stack_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tech_stack',
            new_name='stacks',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='stack',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='stacks/'),
        ),
    ]
